Add white space tests to GitHub actions
Atdding tests to GitHub actions to check for un-wanted whitespace of tabs in Fortran files.

diff --git a/.github/workflows/build_ubuntu_gnu.yml b/.github/workflows/build_ubuntu_gnu.yml
--- a/.github/workflows/build_ubuntu_gnu.yml
+++ b/.github/workflows/build_ubuntu_gnu.yml
@@ -1,8 +1,39 @@
-name: Build FMS Ubuntu GNU
+name: libFMS tests
 
 on: [push, pull_request]
 
 jobs:
+  whitespace:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check code
+        uses: actions/checkout@v2
+      - name: Check for trailing white spaces
+        id: twspace
+        run: |
+          find . -type f -not -path "./.git/*" -exec egrep -l " +$" {} \; | tee files_trailwspace.txt
+          echo "::set-output name=nfiles::$(wc -l files_trailwspace | awk '{print $1}')"
+      - name: Check Fortran for tabs
+        id: ftntab
+        run: |
+          find . -type f -and \( -name \*.INC -or -name \*.inc -or \
+                                 -name \*.fh -or -name \*.FH -or \
+                                 -name \*.\[fF\]90 -or -name \*.\[fF\] \) \
+                                 -exec grep -l '\t' {}  \; | tee files_tabs.txt
+          echo "::set-output name=nfiles::$(wc -l files_tabs.txt | awk '{print $1}')"
+      - name: Check for Failure
+        run: |
+          if test ${{ steps.twspace.outputs.nfiles }} -gt 0 || \
+             test ${{ steps.ftntab.outputs.nfiles }} -gt 0
+          then
+            echo "::error One or more files have trailing white space or one or more Fortran files have tab characters"
+            exit 1
+          fi
+      - name: Report Artifacts
+        uses: actions/upload-artifact@v1
+        with:
+          name: non-compliant-files
+          path: files_*.txt
   build:
     runs-on: ubuntu-latest
     strategy:
